---
hetzner_token: ENV[HCLOUD_TOKEN]
cluster_name: virtual-cv
kubeconfig_path: ./kubeconfig
k3s_version: v1.35.0+k3s3

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: ~/.ssh/github_private.pub
    private_key_path: ~/.ssh/github_private
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0

schedule_workloads_on_masters: true

masters_pool:
  instance_type: cx33
  instance_count: 1
  location: hel1
